apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dummy
spec:
  template:
    spec:
      serviceAccountName: valkey-manager
      containers:
      - name: manager
        image: ghcr.io/tkhq/valkey-manager@sha256:f82446446348824e648ac4deedaa3ba802545b7d19f272995b0aeca7e3e887a3
        resources:
          requests:
            memory: 50Mi
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
        ports:
        - name: manager
          containerPort: 8087
        livenessProbe:
          httpGet:
            path: /healthz
            port: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
