apiVersion: v1
kind: ServiceAccount
metadata:
  name: valkey-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: valkey-manager
rules:
  - apiGroups: 
      - apps
    resources:
      - statefulsets
    verbs: 
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: valkey-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: valkey-manager
subjects:
- kind: ServiceAccount
  name: valkey-manager
